### ISSUE TITLE
undefined reference to `dladdr'

### ISSUE THREAD

**Issue by bichar4** [SchrodingerZhu/stanford-cpp-library-cmake#1]
In ubuntu 18.06 system, had following link error while building the project, 

`libstanford.a(call_stack_gcc.cpp.o): In function `stacktrace::call_stack::call_stack(unsigned long)':`
`call_stack_gcc.cpp:(.text+0x95b): undefined reference to `dladdr'`
`collect2: error: ld returned 1 exit status`
`CMakeFiles/app.dir/build.make:95: recipe for target 'app' failed`
`make[2]: *** [app] Error 1`
`CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/app.dir/all' failed`
`make[1]: *** [CMakeFiles/app.dir/all] Error 2`
`Makefile:83: recipe for target 'all' failed`
`make: *** [all] Error 2`

Solved after adding following lines to CMakeLists.txt file
  `target_link_libraries(${PROJECT_NAME}`   
    `PUBLIC ${Boost_STACKTRACE_BASIC_LIBRARY}`   
    `PUBLIC ${Boost_STACKTRACE_BACKTRACE_LIBRARY}`   
    `PUBLIC ${Boost_STACKTRACE_ADDR2LINE_LIBRARY}`    
    `PUBLIC ${Boost_STACKTRACE_NOOP_LIBRARY}`
   ` PUBLIC pthread dl`
`)`

**Comment by ahmedmustahid** [comment]
I had to export the path of the directory containing `spl.jar` to execute the `app` executable from the project root directory. 
`export SPL_HOME=$PWD/lib`
